// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: frontdeskpb/frontdesk.proto

package frontdeskpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FrontDeskService_CheckAvailability_FullMethodName = "/frontdeskpb.FrontDeskService/CheckAvailability"
)

// FrontDeskServiceClient is the client API for FrontDeskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontDeskServiceClient interface {
	CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest, opts ...grpc.CallOption) (*CheckAvailabilityResponse, error)
}

type frontDeskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontDeskServiceClient(cc grpc.ClientConnInterface) FrontDeskServiceClient {
	return &frontDeskServiceClient{cc}
}

func (c *frontDeskServiceClient) CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest, opts ...grpc.CallOption) (*CheckAvailabilityResponse, error) {
	out := new(CheckAvailabilityResponse)
	err := c.cc.Invoke(ctx, FrontDeskService_CheckAvailability_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrontDeskServiceServer is the server API for FrontDeskService service.
// All implementations must embed UnimplementedFrontDeskServiceServer
// for forward compatibility
type FrontDeskServiceServer interface {
	CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error)
	mustEmbedUnimplementedFrontDeskServiceServer()
}

// UnimplementedFrontDeskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFrontDeskServiceServer struct {
}

func (UnimplementedFrontDeskServiceServer) CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAvailability not implemented")
}
func (UnimplementedFrontDeskServiceServer) mustEmbedUnimplementedFrontDeskServiceServer() {}

// UnsafeFrontDeskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontDeskServiceServer will
// result in compilation errors.
type UnsafeFrontDeskServiceServer interface {
	mustEmbedUnimplementedFrontDeskServiceServer()
}

func RegisterFrontDeskServiceServer(s grpc.ServiceRegistrar, srv FrontDeskServiceServer) {
	s.RegisterService(&FrontDeskService_ServiceDesc, srv)
}

func _FrontDeskService_CheckAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontDeskServiceServer).CheckAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontDeskService_CheckAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontDeskServiceServer).CheckAvailability(ctx, req.(*CheckAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FrontDeskService_ServiceDesc is the grpc.ServiceDesc for FrontDeskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FrontDeskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frontdeskpb.FrontDeskService",
	HandlerType: (*FrontDeskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAvailability",
			Handler:    _FrontDeskService_CheckAvailability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontdeskpb/frontdesk.proto",
}
