---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-trivago-local
labels:
  - includeTemplates: true
    pairs:
      otel-trivago/env: "local"

resources:
  - ../../base

patchesStrategicMerge:
  - svc-reservation.yaml
  - svc-room.yaml

configMapGenerator:
  - name: svc-reservation
    files:
      - configs/reservations.yaml
  - name: svc-room
    files:
      - configs/rooms.yaml
