---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: room
          env:
            - name: CONFIG
              value: "./configs/config.yaml"
          volumeMounts:
            - mountPath: /configs
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: svc-room
            items:
              - key: rooms.yaml
                path: config.yaml

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: svc-room
---
