---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room
spec:
  replicas: 2
  template:
    metadata:
      labels:
        otel-trivago/allow-ingress: "default"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: room
          env:
            - name: CONFIG
              value: "./configs/config.yaml"
          volumeMounts:
            - mountPath: /configs
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: svc-room
            items:
              - key: rooms.yaml
                path: config.yaml
---
