---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: reservation
          env:
            - name: CONFIG
              value: "./configs/config.yaml"
          volumeMounts:
            - mountPath: /configs
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: svc-reservation
            items:
              - key: reservations.yaml
                path: config.yaml

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: svc-reservation
---
