---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: reservation
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4317
