apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - svc-reservation.yaml
  - svc-room.yaml
  - svc-frontdesk.yaml

images:
  - name: trivago-image
    newName: docker.io/falmar/otel-trivago
    newTag: 91458725
