apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - svc-reservation.yaml
  - svc-room.yaml
  - svc-frontdesk.yaml

images:
  - name: reservation-image
    newName: docker.io/falmar/otel-trivago
    newTag: reservation-3fe245f9
  - name: room-image
    newName: docker.io/falmar/otel-trivago
    newTag: room-3fe245f9
  - name: frontdesk-image
    newName: docker.io/falmar/otel-trivago
    newTag: frontdesk-3fe245f9
  - name: stay-image
    newName: docker.io/falmar/otel-trivago
    newTag: stay-3fe245f9
