apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - svc-reservation.yaml
  - svc-room.yaml
  - svc-stay.yaml
  - svc-frontdesk.yaml

images:
  - name: reservation-image
    newName: docker.io/falmar/otel-trivago
    newTag: reservation
  - name: room-image
    newName: docker.io/falmar/otel-trivago
    newTag: room
  - name: stay-image
    newName: docker.io/falmar/otel-trivago
    newTag: stay
  - name: frontdesk-image
    newName: docker.io/falmar/otel-trivago
    newTag: frontdesk
