---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: room-ingress
spec:
  podSelector:
    matchLabels:
      otel-trivago/app: "room"
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              otel-trivago/app: "frontdesk"
      ports:
        - protocol: TCP
          port: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: room
spec:
  replicas: 3
  selector:
    matchLabels:
      otel-trivago/app: room
  template:
    metadata:
      labels:
        otel-trivago/app: room
        otel-trivago/grpc-otlp: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: room
          imagePullPolicy: Always
          image: room-image
          env:
            - name: PROMETHEUS_METRICS_PORT
              value: "9090"
          ports:
            - containerPort: 80
              name: grpc
            - containerPort: 9090
              name: metrics
---

apiVersion: v1
kind: Service
metadata:
  name: room
  labels:
    otel-trivago/app: room
spec:
  selector:
    otel-trivago/app: room
  type: ClusterIP
  ports:
    - protocol: TCP
      name: grpc
      port: 80
    - protocol: TCP
      name: metrics
      port: 9090
---
