---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
spec:
  replicas: 3
  selector:
    matchLabels:
      otel-trivago/app: reservation
  template:
    metadata:
      labels:
        otel-trivago/app: reservation
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: reservation
          imagePullPolicy: Always
          image: reservation-image
          env:
            - name: PROMETHEUS_METRICS_PORT
              value: "9090"
          ports:
            - containerPort: 80
              name: grpc
            - containerPort: 9090
              name: metrics
---

apiVersion: v1
kind: Service
metadata:
  name: reservation
  labels:
    otel-trivago/app: reservation
spec:
  selector:
    otel-trivago/app: reservation
  type: ClusterIP
  ports:
    - protocol: TCP
      name: grpc
      port: 80
    - protocol: TCP
      name: metrics
      port: 9090
---
