---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
spec:
  replicas: 3
  selector:
    matchLabels:
      otel-trivago/app: reservation
  template:
    metadata:
      labels:
        otel-trivago/app: reservation
    spec:
      containers:
        - name: reservation
          imagePullPolicy: Always
          image: docker.io/falmar/otel-trivago:reservation
          env:
            - name: PORT
              value: "80"
            - name: ROOM_HOST
              value: "room:80"
          ports:
            - containerPort: 80
              name: grpc
---

apiVersion: v1
kind: Service
metadata:
  name: reservation
  labels:
    otel-trivago/app: reservation
spec:
  selector:
    otel-trivago/app: reservation
  type: NodePort
  ports:
    - protocol: TCP
      name: grpc
      port: 80
      targetPort: grpc
      nodePort: 30080
---
