service:
  name: "reservations"
  port: "8080"

# grpc endpoint for the otpl collector
otpl_endpoint: "http://localhost:4317"

prometheus:
  metrics:
    enable: false
    port: "8190"
    path: "/metrics"

rooms:
  endpoint: "localhost:8081"
