service:
  name: "frontdesk"
  port: "8083"

# grpc endpoint for the otlp collector
otpl_endpoint: "localhost:4317"

prometheus:
  metrics:
    enable: false
    port: "8193"
    path: "/metrics"

reservations:
  endpoint: "localhost:8080"
rooms:
  endpoint: "localhost:8081"
