name: deploy
on:
  push:
    branches:
      - master

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  push_images:
    needs: tests
    runs-on: ubuntu-latest
    env:
      platform: linux/amd64,linux/arm64
      DOCKER_IMAGE: docker.io/${{ secrets.HUB_USERNAME }}/otel-trivago
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.platform }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Short Commit SHA
        id: short_sha
        run: echo "commit_id=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.platform }}
          context: .
          target: output
          push: true
          file: ./build/Dockerfile
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.short_sha.outputs.commit_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  commit:
    runs-on: ubuntu-latest
    needs: push_images
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Short Commit SHA
        id: short_sha
        run: echo "commit_id=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Update YAML File
        run: |
          sed -i "s/newTag: [^ ]*/newTag: ${{ steps.short_sha.outputs.commit_id }}/" deployments/base/kustomization.yaml      

      - uses: stefanzweifel/git-auto-commit-action@v5
